name: Update README
# This workflow checks my blog for the latest posts
#

on: [push, merge]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # All the Prep Work
      - name: Checkout Main
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
          architecture: "x64"

      - name: Install Jinja2
        run: pip install -r requirements.txt

      - name: Update Readme
        run: python ./src/render.py

      - name: load to github
        run: |
          git config user.name "Automated Publisher"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m ":robot: Automated update README: ${timestamp}" || exit 0
          g
